version: '3.6'
services:
  users:
    build:
      context: ./services/users
      dockerfile: Dockerfile-stage
      cache_from:
          - 929568017084.dkr.ecr.us-east-1.amazonaws.com/test-driven-users:e2e
    image: 929568017084.dkr.ecr.us-east-1.amazonaws.com/test-driven-users:e2e
    expose:
      - 5000
    environment:
      - FLASK_ENV=production
      - APP_SETTINGS=project.config.StagingConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_stage
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
      - SECRET_KEY=my_precious
    depends_on:
      - users-db
  users-db:
    build:
      context: ./services/users/project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  builder:
    container_name: builder
    build:
      context: ./services/client
      dockerfile: Dockerfile-stage
      target: builder
      args:
        - NODE_ENV=production
        - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
      cache_from:
          - 929568017084.dkr.ecr.us-east-1.amazonaws.com/test-driven-client:builder
    image: 929568017084.dkr.ecr.us-east-1.amazonaws.com/test-driven-client:builder
  client:
    container_name: client
    build:
      context: ./services/client
      dockerfile: Dockerfile-stage
      target: client
      args:
        - NODE_ENV=production
        - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
      cache_from:
          - 929568017084.dkr.ecr.us-east-1.amazonaws.com/test-driven-client:builder
          - 929568017084.dkr.ecr.us-east-1.amazonaws.com/test-driven-client:e2e
    image: 929568017084.dkr.ecr.us-east-1.amazonaws.com/test-driven-client:e2e
    expose:
      - 80
    depends_on:
      - users
  swagger:
    build:
      context: ./services/swagger
      dockerfile: Dockerfile-stage
      cache_from:
          - 929568017084.dkr.ecr.us-east-1.amazonaws.com/test-driven-swagger:e2e
    image: 929568017084.dkr.ecr.us-east-1.amazonaws.com/test-driven-swagger:e2e
    expose:
      - 8080
    environment:
      - URL=swagger.json
    depends_on:
      - users
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-stage
    restart: always
    ports:
      - 80:80
    depends_on:
      - users
      - client
